<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Data\**" />
    <Compile Remove="Domain\**" />
    <Content Remove="Data\**" />
    <Content Remove="Domain\**" />
    <EmbeddedResource Remove="Data\**" />
    <EmbeddedResource Remove="Domain\**" />
    <None Remove="Data\**" />
    <None Remove="Domain\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.20">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.20" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CabinReservation.Persistence\CabinReservation.Persistence.csproj" />
  </ItemGroup>
</Project>
